config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :invites, only: [:new, :index, :edit, :update, :create, :destroy]
  end

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
    
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: :show

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "events#index"
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :attended_event, class_name: "Event"
  belongs_to :attendee, class_name: "User"

  validates :status, inclusion: { in: ['Invited', 'Attending', 'Not Attending'] }
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
  before_action :authenticate_user!

  def create
    @invite = Invite.new(invite_params)
    @event = Event.find(params[:event_id])

    if @invite.save
      redirect_to event_invites_path(@event)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @event = Event.find(params[:event_id])
  end

  def update
    @invite = Invite.find(params[:id])

    if @invite.update(invite_params)
      redirect_to Event.find(invite_params[:attended_event_id]), notice: "You are now attending this event."
    else
      render Event.find(invite_params[:attended_event_id]), notice: "There was an error."
    end
  end

  def destroy
    @event = Event.find(params[:event_id])
    @invite = Invite.find(params[:id])
    @invite.destroy

    redirect_to event_invites_path(Event.find(@invite.attended_event_id)), notice: "You are no longer attending this event."
  end

  private

  def invite_params
    params.require(:invite).permit(:attended_event_id, :attendee_id, :status)
  end
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/views/invites/_attendance.html.erb
<p class="p-2">Status: <%= invite.status %></p>

<% if invite.status == "Invited" || invite.status == "Not Attending" %>
  <div >
    <%= form_with model: [event, invite] do |f| %>
      <%= f.hidden_field :status, value: "Attending" %>
      <div class="p-2 underline text-blue-500 "><%= f.submit "Attend this event" %></div>
    <% end %>
  </div>
<% elsif invite.status == "Attending" %>
  <%= form_with model: [event, invite] do |f| %>
    <%= f.hidden_field :status, value: "Not Attending" %>
    <div class="p-2 underline text-blue-500 "><%= f.submit "I'm no longer attending this event" %></div>
  <% end %>
<% end %>

app/views/invites/index.html.erb
<%= image_tag "placeholder.jpg" %>
<div class="p-2"><%= @event.name %></div>
<div class="p-2">Created by: <%= "#{@event.creator.first_name} #{@event.creator.last_name}" %></div>
<div class="p-2"><%= "#{Date::MONTHNAMES[@event.date.month]} #{@event.date.day}, #{@event.date.year}" %> <%= @event.time.to_fs(:time)%></div>

<% User.where("id <> ?", @event.creator.id).each do |user| %>
  <div class="flex gap-2 items-center m-2">
    <!-- Uninvite a user who has been invited -->
    <% if user.invites.where(attended_event_id: @event.id).exists? %>
      <div class="border border-black border-solid rounded-md px-2 py-1">
        <%= button_to "Uninvite", event_invite_path(@event, user.invites.find_by(attended_event_id: @event.id)), method: :delete %>
      </div>
    <% else %>
    <!-- Invite user who is not invited -->
      <div class="border border-black border-solid rounded-md px-2 py-1">
        <%= form_with model: [@event, Invite.new] do |f| %>
          <%= f.hidden_field :attended_event_id, value: @event.id %>
          <%= f.hidden_field :attendee_id, value: user.id %>
          <%= f.hidden_field :status, value: "Invited" %>
          <%= f.submit "Invite" %>
        <% end %>
      </div>
    <% end %>
    <div>
      <%= "#{user.first_name} #{user.last_name}" %> -
    </div>
    <div>
      <% if user.invites.where(attended_event_id: @event.id).exists? %>
        <%= user.invites.find_by(attended_event_id: @event.id).status %>
      <% else %>
        <div>Not Invited</div>
      <% end %>
    </div>
  </div>
<% end %>