config/routes.rb
Rails.application.routes.draw do
  resources :events do
    resources :invites, only: [:new, :index, :edit, :update, :create, :destroy]
  end

  devise_scope :user do
    # Redirests signing out users back to sign-in
    get "users", to: "devise/sessions#new"
  end
    
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users, only: :show

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, presence: true
  validates :date, presence: true
  validates :time, presence: true

  belongs_to :creator, class_name: "User"
  has_many :invites, foreign_key: "attended_event_id"
  has_many :attendees, through: :invites, source: :users, foreign_key: "attendee_id"

  scope :past, -> { where("date < ?", Date.today) }
  scope :upcoming, -> { where("date > ?", Date.today) }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /events
  def index
    @events = Event.where(id: Invite.where(attendee_id: current_user.id).select(:attended_event_id)).or(Event.where(creator_id: current_user))
  end

  # GET /events/1
  def show
    accepted_invites = Invite.where(attended_event_id: @event.id).where(status: "Attending")
    @attendees = User.where(id: accepted_invites.select(:attendee_id))
    @invite = @event.invites.find_by(attendee_id: current_user.id)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = Event.new(event_params)

    if @event.save 
      redirect_to event_url(@event), notice: "Event was successfully created." 
    else
        render :new, status: :unprocessable_entity 
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to event_url(@event), notice: "Event was successfully updated." 
    else
      render :edit, status: :unprocessable_entity 
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: "Event was successfully destroyed." 
  end

  private
  
  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :date, :time, :creator_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>" class="w-72 m-6 border-2 border-black rounded-lg">
  <%= image_tag "placeholder.jpg" %>
  <div class="p-2"><%= event.name %></div>
  <div class="p-2">Created by: <%= "#{event.creator.first_name} #{event.creator.last_name}" %></div>
  <div class="p-2"><%= "#{Date::MONTHNAMES[event.date.month]} #{event.date.day} #{event.date.year}" %> <%= event.time.to_fs(:time)%></div>

  <% if user_signed_in? && event.invites.where(attendee_id: current_user.id).exists? %>
    <%= render partial: "invites/attendance", locals: { event: event, invite: event.invites.find_by(attendee_id: current_user.id) } %>
  <% end %>

  <p class="p-2 underline text-blue-400">
    <%= link_to "Show this event", event %>
  </p>
</div>

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :creator_id, value: current_user.id %>

  <div>
    <div class="field">
      <%= form.label :name %><br />
      <%= form.text_field :name %>
    </div>

    <div class="field">
      <%= form.label :date %><br />
      <%= form.date_select :date, order: [:month, :day, :year] %>
    </div>

    <div class="field">
      <%= form.label :time %><br />
      <%= form.time_select :time %>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Show this event", @event %> |
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="mx-6 mt-6 font-semibold text-xl">Upcoming Events</h1>
<div id="events" class="flex flex-wrap">
  <% @events.upcoming.each do |event| %>
    <div><%= render event %></div>
  <% end %>
</div>

<h1 class="mx-6 font-semibold text-xl">Past Events</h1>
<div id="events" class="flex flex-wrap">
  <% @events.past.each do |event| %>
    <div><%= render event %></div>
  <% end %>
</div>

<% if user_signed_in? %>
  <div class="mx-8 mb-6 underline text-blue-400"><%= link_to "New event", new_event_path %></div>
<% end %>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= image_tag "placeholder.jpg" %>
<div class="p-2"><%= @event.name %></div>
<div class="p-2">Created by: <%= "#{@event.creator.first_name} #{@event.creator.last_name}" %></div>
<div class="p-2"><%= "#{Date::MONTHNAMES[@event.date.month]} #{@event.date.day}, #{@event.date.year}" %> <%= @event.time.to_fs(:time)%></div>

<% if current_user == @event.creator %>
  <div class="p-2">
    <%= link_to "Invite users", event_invites_path(@event) %>
  </div>
<% end %>

<% unless current_user == @event.creator %>
  <%= render partial: "invites/attendance", locals: { event: @event, invite: @invite } %>
<% end %>

<div class="border border-gray-500 border-solid w-1/2 m-2">
  <div class="p-2 underline semibold text-lg">Attendees</div>
  <div class="p-2">
    <%= @event.creator.first_name %> <%= @event.creator.last_name %>
  </div>
  <%  @attendees.each do |attendee| %>
    
    <div class="p-2">
      <%= attendee.first_name %>
      <%= attendee.last_name %>
    </div>
  <% end %>
</div>

<div class="p-2">
  <%= link_to "Edit this event", edit_event_path(@event) %> |
  <%= link_to "Back to events", events_path %>

  <%= button_to "Destroy this event", @event, method: :delete %>
</div>